rank1 = [
    "シャイニーカラーズ",
    "song for prism",
    "シャニマス",
    "シャニソン",
    "シャニアニ",
    "ジムシャニ",
    "シャニ",
    "イルミネーションスターズ",
    "アンティーカ",
    "放課後クライマックスガールズ",
    "アルストロメリア",
    "ストレイライト",
    "ノクチル",
    "シーズ",
    "コメティック",
    "櫻木真乃",
    "風野灯織",
    "八宮めぐる",
    "月岡恋鐘",
    "田中摩美々",
    "白瀬咲耶",
    "三峰結華",
    "幽谷霧子",
    "小宮果穂",
    "園田智代子",
    "西城樹里",
    "杜野凛世",
    "有栖川夏葉",
    "大崎甘奈",
    "大崎甜花",
    "桑山千雪",
    "芹沢あさひ",
    "黛冬優子",
    "和泉愛依",
    "浅倉透",
    "樋口円香",
    "福丸小糸",
    "市川雛菜",
    "七草にちか",
    "緋田美琴",
    "斑鳩ルカ",
    "鈴木羽那",
    "郁田はるき",
    "天井努",
    "七草はづき",
    "シャニP",
    "デビ太郎",
    "エン次郎",
    "ユアクマ",
    "マメ丸",
    "W.I.N.G.",
    "G.R.A.D.",
    "S.T.E.P.",
    "283プロダクション",
    "283プロ",
    "イルミネ",
    "放クラ",
    "アルスト",
    "ストレイ",
]

rank2 = [
    "櫻木",
    "風野",
    "八宮",
    "月岡",
    "田中",
    "白瀬",
    "三峰",
    "幽谷",
    "小宮",
    "園田",
    "西城",
    "杜野",
    "有栖川",
    "大崎",
    "桑山",
    "芹沢",
    "黛",
    "和泉",
    "浅倉",
    "樋口",
    "福丸",
    "市川",
    "七草",
    "緋田",
    "斑鳩",
    "鈴木",
    "郁田",
    "真乃",
    "灯織",
    "めぐる",
    "恋鐘",
    "摩美々",
    "咲耶",
    "結華",
    "霧子",
    "果穂",
    "智代子",
    "樹里",
    "凛世",
    "夏葉",
    "甘奈",
    "甜花",
    "千雪",
    "あさひ",
    "冬優子",
    "愛依",
    "透",
    "円香",
    "小糸",
    "雛菜",
    "にちか",
    "美琴",
    "ルカ",
    "羽那",
    "はるき",
    "努",
    "はづき",
    "ピーちゃん",
    "カトレア",
]
