rank1 = [
    "シャイニーカラーズ",
    "song for prism",
    "シャニマス",
    "シャニソン",
    "シャニアニ",
    "ジムシャニ",
    "シャニ",
    "コヒーレントライト",
    "イルミネーションスターズ",
    "アンティーカ",
    "放課後クライマックスガールズ",
    "アルストロメリア",
    "ストレイライト",
    "ノクチル",
    "シーズ",
    "コメティック",
    "櫻木真乃",
    "風野灯織",
    "八宮めぐる",
    "月岡恋鐘",
    "田中摩美々",
    "白瀬咲耶",
    "三峰結華",
    "幽谷霧子",
    "小宮果穂",
    "園田智代子",
    "西城樹里",
    "杜野凛世",
    "有栖川夏葉",
    "大崎甘奈",
    "大崎甜花",
    "桑山千雪",
    "芹沢あさひ",
    "黛冬優子",
    "和泉愛依",
    "浅倉透",
    "樋口円香",
    "福丸小糸",
    "市川雛菜",
    "七草にちか",
    "緋田美琴",
    "斑鳩ルカ",
    "鈴木羽那",
    "郁田はるき",
    "天井努",
    "七草はづき",
    "シャニP",
    "デビ太郎",
    "エン次郎",
    "ユアクマ",
    "マメ丸",
    "W.I.N.G.",
    "G.R.A.D.",
    "S.T.E.P.",
    "283プロダクション",
    "283プロ",
    "イルミネ",
    "放クラ",
    "アルスト",
    "ストレイ",
    "spread the wings\\!\\!",
    "ヒカリのdestination",
    "バベルシティ・グレイス",
    "夢咲きafter school",
    "multicolored sky",
    "虹になれ",
    "幻惑silhouette",
    "太陽キッス",
    "ハピリリ",
    "let's get a chance",
    "snow flakes memories",
    "ambitious eve",
    "いつか shiny days",
    "wandering dream chaser",
    "we can go now\\!",
    "neo theory fantasy",
    "ラビリンス・レジスタンス",
    "ビーチブレイバー",
    "よりみちサンセット",
    "bloomy\\!",
    "love addiction",
    "transcending the world",
    "futurity smile",
    "sweet♡step",
    "シャイノグラフィ",
    "絶対正義 every day",
    "デビ太郎のうた",
    "dye the sky.",
    "いつだって僕らは",
    "twinkle way",
    "hide & attack",
    "destined rival",
    "あの花のように",
    "happy funny lucky",
    "black reverie",
    "純白トロイメライ",
    "五ツ座流星群",
    "学祭革命夜明け前",
    "ダブル・イフェクト",
    "ありったけの輝きで",
    "チョコデート・サンデー",
    "sweet memories",
    "アポイント・シグナル",
    "ハナマルバッジ",
    "星をめざして",
    "プラニスフィア 〜planisphere〜",
    "プラニスフィア",
    "誰ソ彼アイデンティティー",
    "プラスチック・アンブレラ",
    "わたしの主人公はわたしだから！",
    "常咲の庭",
    "雪・月・風・花",
    "going my way",
    "リフレクトサイン",
    "harebare\\!\\!",
    "damascus cocktail",
    "あおぞらサイダー",
    "過純性ブリーチ",
    "darling you\\!",
    "千夜アリア",
    "solar way",
    "resonance\\+",
    "color days",
    "prisism",
    "スマイルシンフォニア",
    "abyss of conflict",
    "革命進化論",
    "クライマックスアイランド",
    "拝啓タイムカプセル",
    "パステルカラー パスカラカラー",
    "ラブ・ボナペティート",
    "another rampage",
    "timeless shooting star",
    "僕らだけの未来の空",
    "今しかない瞬間を",
    "fly and fly",
    "神様は死んだ、って",
    "secret utopia",
    "相合学舎",
    "killer×mission",
    "虹の行方",
    "daybreak age",
    "イルミネイトコンサート",
    "浮動性イノセンス",
    "愚者の独白",
    "一閃は君が導く",
    "キャットスクワッド",
    "very berry love",
    "give me some more...",
    "283体操",
    "シャイニーエクササイズ",
    "tracing defender",
    "overdrive emotion",
    "catch the breeze",
    "アスファルトを鳴らして",
    "bouncy girl",
    "forward march\\!\\!\\!",
    "星が流れて",
    "brightest white",
    "とある英雄たちの物語",
    "shiny stories",
    "unsung heroes",
    "有彩色ユリイカ",
    "ハナサカサイサイ",
    "全力アンサー",
    "ひめくりモザイク",
    "imitation ghost",
    "フェアリー・ガール",
    "look up to the sky",
    "burn burn",
    "start up stand up",
    "夢が夢じゃなくなるその日まで",
    "青とオレンジ",
    "forbidden paradise",
    "sweetest bite",
    "無自覚アプリオリ",
    "white story",
    "ツバサグラビティ",
    "星の声",
    "くだらないや",
    "平行線の美学",
    "ホムラインビテーション",
]

rank2 = [
    "櫻木",
    "風野",
    "八宮",
    "月岡",
    "田中",
    "白瀬",
    "三峰",
    "幽谷",
    "小宮",
    "園田",
    "西城",
    "杜野",
    "有栖川",
    "大崎",
    "桑山",
    "芹沢",
    "黛",
    "和泉",
    "浅倉",
    "樋口",
    "福丸",
    "市川",
    "七草",
    "緋田",
    "斑鳩",
    "鈴木",
    "郁田",
    "真乃",
    "灯織",
    "めぐる",
    "恋鐘",
    "摩美々",
    "咲耶",
    "結華",
    "霧子",
    "果穂",
    "智代子",
    "樹里",
    "凛世",
    "夏葉",
    "甘奈",
    "甜花",
    "千雪",
    "あさひ",
    "冬優子",
    "愛依",
    "透",
    "円香",
    "小糸",
    "雛菜",
    "にちか",
    "美琴",
    "ルカ",
    "羽那",
    "はるき",
    "努",
    "はづき",
    "ピーちゃん",
    "カトレア",
    "anniversary",
    "夢見鳥",
    "また明日",
    "スローモーション",
    "statice",
    "sos",
    "oh my god",
    "felice",
    "fashionable",
    "グラデーション",
    "メッセージ",
    "love letter",
    "reflection",
]
